/*
Navicat MySQL Data Transfer

Source Server         : root
Source Server Version : 50553
Source Host           : localhost:3306
Source Database       : myblog

Target Server Type    : MYSQL
Target Server Version : 50553
File Encoding         : 65001

Date: 2017-05-17 21:43:33
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for text
-- ----------------------------
DROP TABLE IF EXISTS `text`;
CREATE TABLE `text` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(256) DEFAULT NULL,
  `content` text,
  `date` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of text
-- ----------------------------
INSERT INTO `text` VALUES ('36', 'JUU2JTk3JUEwJUU5JUEyJTk4', 'JTNDcCUzRSUzQy9wJTNFJTNDcCUzRSUzQy9wJTNFJTNDcCUzRSUzQy9wJTNFJTNDcCUyMHN0eWxlPSUyMnRleHQtYWxpZ246JTIwY2VudGVyOyUyMCUyMiUzRSUzQ2ZvbnQlMjBmYWNlPSUyMiVFNSVCRSVBRSVFOCVCRCVBRiVFOSU5QiU4NSVFOSVCQiU5MSUyMiUyMHNpemU9JTIyNSUyMiUzRSVFNyU5QiVCOCVFOCVBNyU4MSVFNiU5NyVCNiVFOSU5QSVCRSVFNSU4OCVBQiVFNCVCQSVBNiVFOSU5QSVCRSVFRiVCQyU4QyVFNCVCOCU5QyVFOSVBMyU4RSVFNiU5NyVBMCVFNSU4QSU5QiVFNyU5OSVCRSVFOCU4QSVCMSVFNiVBRSU4QiVFMyU4MCU4MiUzQy9mb250JTNFJTNDL3AlM0UlM0NwJTIwc3R5bGU9JTIydGV4dC1hbGlnbjolMjBjZW50ZXI7JTIwJTIyJTNFJTNDZm9udCUyMGZhY2U9JTIyJUU1JUJFJUFFJUU4JUJEJUFGJUU5JTlCJTg1JUU5JUJCJTkxJTIyJTIwc2l6ZT0lMjI1JTIyJTNFJUU2JTk4JUE1JUU4JTlBJTk1JUU1JTg4JUIwJUU2JUFEJUJCJUU0JUI4JTlEJUU2JTk2JUI5JUU1JUIwJUJEJUVGJUJDJThDJUU4JTlDJUExJUU3JTgyJUFDJUU2JTg4JTkwJUU3JTgxJUIwJUU2JUIzJUFBJUU1JUE3JThCJUU1JUI5JUIyJUUzJTgwJTgyJTNDL2ZvbnQlM0UlM0MvcCUzRSUzQ3AlMjBzdHlsZT0lMjJ0ZXh0LWFsaWduOiUyMGNlbnRlcjslMjAlMjIlM0UlM0Nmb250JTIwZmFjZT0lMjIlRTUlQkUlQUUlRTglQkQlQUYlRTklOUIlODUlRTklQkIlOTElMjIlMjBzaXplPSUyMjUlMjIlM0UlRTYlOTklOTMlRTklOTUlOUMlRTQlQkQlODYlRTYlODQlODElRTQlQkElOTElRTklQUMlOTMlRTYlOTQlQjklRUYlQkMlOEMlRTUlQTQlOUMlRTUlOTAlOUYlRTUlQkElOTQlRTglQTclODklRTYlOUMlODglRTUlODUlODklRTUlQUYlOTIlRTMlODAlODIlM0MvZm9udCUzRSUzQy9wJTNFJTNDcCUyMHN0eWxlPSUyMnRleHQtYWxpZ246JTIwY2VudGVyOyUyMCUyMiUzRSUzQ2ZvbnQlMjBmYWNlPSUyMiVFNSVCRSVBRSVFOCVCRCVBRiVFOSU5QiU4NSVFOSVCQiU5MSUyMiUyMHNpemU9JTIyNSUyMiUzRSVFOCU5MyVBQyVFNSVCMSVCMSVFNiVBRCVBNCVFNSU4RSVCQiVFNiU5NyVBMCVFNSVBNCU5QSVFOCVCNyVBRiVFRiVCQyU4QyVFOSU5RCU5MiVFOSVCOCU5RiVFNiVBRSVCNyVFNSU4QiVBNCVFNCVCOCVCQSVFNiU4RSVBMiVFNyU5QyU4QiVFMyU4MCU4MiUzQy9mb250JTNFJTNDL3AlM0UlM0NwJTNFJTNDYnIlM0UlM0MvcCUzRSUzQ3AlM0UlM0NiciUzRSUzQy9wJTNFJTNDcCUzRSUzQ2ltZyUyMHN0eWxlPSUyMm1heC13aWR0aDoxMDAlMjU7JTIyJTIwc3JjPSUyMmh0dHBzOi8vdGltZ3NhLmJhaWR1LmNvbS90aW1nP2ltYWdlJnF1YWxpdHk9ODAmYW1wO3NpemU9Yjk5OTlfMTAwMDAmYW1wO3NlYz0xNDk0OTQ5NTQ1ODkyJmFtcDtkaT1hYWY0MzQ0NGM1OTg2OTQ3MDIxOTRkNWVjNzY4OWNjNiZhbXA7aW1ndHlwZT0wJmFtcDtzcmM9aHR0cCUyNTNBJTI1MkYlMjUyRnBpYzM1Lm5pcGljLmNvbSUyNTJGMjAxMzExMDklMjUyRjEzNDcyNTM2XzAxMDMwMjMyOTAwMF8yLmpwZyUyMiUzRSUzQy9wJTNFJTNDcCUzRSUzQy9wJTNFJTNDcCUzRSUzQ2JyJTNFJTNDL3AlM0UlM0NwJTNFJTNDL3AlM0UlM0NwJTNFJTNDYnIlM0UlM0MvcCUzRSUzQ3AlM0UlM0MvcCUzRSUzQ3AlM0UlM0MvcCUzRQ', '2017-05-17');
INSERT INTO `text` VALUES ('40', 'JUU0JUJEJUEwJUU2JTg4JTkx', 'JTNDcCUzRSUzQ2ltZyUyMHNyYz0lMjJodHRwOi8vbG9jYWxob3N0OjgwODAvdXBsb2FkLzhlODQ4NjZkLWJjOTctNGEyNS1hNDRhLTVmNzgwODNiYjgyNy5qcGclMjIlMjBhbHQ9JTIyMDQyNzNjN2IyMzJiNjEyZjZiNjViMjE1YmFjY2JiY2FlYjY0NzIzOCUyMiUyMHN0eWxlPSUyMm1heC13aWR0aDoxMDAlMjU7JTIyJTNFJTNDL3AlM0UlM0NwJTNFJTNDL3AlM0UlM0NwJTNFJTNDYnIlM0UlM0MvcCUzRQ', '2017-05-17');
INSERT INTO `text` VALUES ('41', 'amF2YQ', 'JTNDcCUzRWphdmElRTYlOTglQUYlRTQlQjglODAlRTklOTclQTglRTclQTUlOUUlRTUlQTUlODclRTclOUElODQlRTglQUYlQUQlRTglQTglODAlRTMlODAlODIlM0MvcCUzRSUzQ3AlM0UlM0MvcCUzRSUzQ3AlM0UlM0NpbWclMjBzdHlsZT0lMjJtYXgtd2lkdGg6MTAwJTI1OyUyMiUyMHNyYz0lMjJodHRwOi8vd3d3Lmhhb3JhY2xlLmNvbS91cGxvYWRzL2FsbGltZy8xNjA3MDUvMS0xNjBGNTE0MTIzM0g4LmpwZyUyMiUzRSUzQ2JyJTNFJTNDL3AlM0UlM0NwJTNFJTNDYnIlM0UlM0MvcCUzRQ', '2017-05-17');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` varchar(255) NOT NULL DEFAULT '' COMMENT '用户名',
  `name` varchar(255) DEFAULT NULL COMMENT '用户名',
  `role` varchar(25) DEFAULT NULL COMMENT '角色',
  `password` varchar(32) DEFAULT NULL COMMENT '加盐后用户密码',
  `salt` varchar(6) DEFAULT NULL COMMENT 'MD5盐',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户登录表';

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('buyulian', null, 'admin', '21cb5aeb5d8af41f0dd397ba93c5399d', 'geoTAB');
INSERT INTO `user` VALUES ('standard', null, 'standard', '31a02d7af09cf30c604c6a228450ebc7', 'YmkTl2');
